improve travis build
+ independent build 6 jobs: (jdk8, 11) x (scala 2.11, 2.12, 2.13)
+ use build & updateArchives tasks in each job instead of buildAll & uploadArchivesAll
+ travis cache
+ only checkScoverage once on job jdk11 + scala 2.12

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,14 +1,46 @@
 language: java
-jdk: openjdk8
-#addons:
-#  apt:
-#    packages:
-#      - oracle-java8-installer
+os: linux
+jdk:
+  - openjdk11
+  - openjdk8
 env:
+  jobs:
+    # https://docs.gradle.org/current/userguide/build_environment.html#sec:project_properties
+    - ORG_GRADLE_PROJECT_scalaVersion=2.13.1
+    - ORG_GRADLE_PROJECT_scalaVersion=2.12.10
+    - ORG_GRADLE_PROJECT_scalaVersion=2.11.12
   global:
-  - secure: fIwS3wctOKMs+yEE8s4lvtcwJEgktzHCliK+D7ShJ8Lia98JWCc/JhGMlCtX3RFkQjIy0syIJKw2eQglxNqqFqoO7EsQhipgf9An+hVVbw/Tn7t1xIslSw9EzFUTRA/wP00JLKunUizR6YxuLmq9VbxzJdK+kr5v1g3ggq311sKE8bpWWqTvixKkhQg2ULyqHZ3cPcMnxAmLG8jiddgnN7PcDL0MOePiSQeNawwFNoI7rp6rZRfREHyrHrwIo7USfPP8R8Mk0z9b08MxW0ZG4P04M0jWZRobqXMYz/PW2GALn0UQPDjg+8OI4qtmmunPYR0mwkgRumpem8LhIjHoOXZu/Oq8OqU+76x/gcEU25nkz3EH59si/kGOxObJUFUil6pt4QjA/QSI7dzC+yQIabOfJEOH8D3q9Eb6JBRWIf26pj02b2IbWmPFEooxQXL7XNQ/eYmnrw0UhOQvBPJ+YntQmpHlJKNwPD5lIOrqvLWoUWYe5oB83o2G2CyybzuPBrioUxr4XcGFiq4W5X3rjCQpNHTPS1QOPLukisYMdXQPkcTsvcrEUHvA2bH6a2gmvG7ykR9iHqPrpARqxt1qO84RbgK/pJhNcayZKRDrNjxHxiaQJXT5xlIjld1uxAM7kRUunuWNm57gi170LveMFK668PVcUAQTrD09eosrbKQ=
-  - secure: MlwQtz4tO1mmNmPE2PIxYI552puyQpQa690C6ZOldvL0zGhw5mgj5JD8G4I4RmuaNev7mpdnBecoTEg6q2pxPTHQEgQmHVX5X7SPf1Loyes35AWzscGhWVwFdOF6ZqccB8PUZrUZ2CAD83JjG39/PGk5bxqwBNFkeFBQrGYhDuL5caqJ9/MTfKHM/NoR66ygigscnsfb8qwtS1wpSJ5LbFrC2KFzGfDXuP5bjkz9PZdQrS8c7nC63KcdeENpqwdrWWzrw3hf0uSh3xEZp7SziDZ0wMOX6lmIIzRjmlJIPF4BD9MsDiPqhmwJk4MdvKtWAzKJTnGxmygNLVw7YKnqULnWjsOmNfraHGEkqSE/DCccsjAIzYP0vD7V+JgXOk5JLvwLGff3VW9457f2pAMWJgliL9r136DKLMvxiMpXgFp3BkZHsc80Ve1G9nqgGMqp1zrCgE78mqQJ5AFQczfTZOXNsjLkGYgs38k7aLiCAm8p9ZHYBo4DZiaPKc/K2XkBmTP+2KuHpwXGUbnvfFFoHuwV1iDh+CeEo1N4UZrhwPCXTNaJKYQCQ8d7u2Vvt27Ido+IfvSnKvBlHMkpmzAdyF5dhT3jR0xEartpMw8MmUnKVxanJitfLME1qInf7INhFkkRECj9yFpFA1kCM+dszxdEEaBmD0D004xd0rU4Y3c=
+    - secure: fIwS3wctOKMs+yEE8s4lvtcwJEgktzHCliK+D7ShJ8Lia98JWCc/JhGMlCtX3RFkQjIy0syIJKw2eQglxNqqFqoO7EsQhipgf9An+hVVbw/Tn7t1xIslSw9EzFUTRA/wP00JLKunUizR6YxuLmq9VbxzJdK+kr5v1g3ggq311sKE8bpWWqTvixKkhQg2ULyqHZ3cPcMnxAmLG8jiddgnN7PcDL0MOePiSQeNawwFNoI7rp6rZRfREHyrHrwIo7USfPP8R8Mk0z9b08MxW0ZG4P04M0jWZRobqXMYz/PW2GALn0UQPDjg+8OI4qtmmunPYR0mwkgRumpem8LhIjHoOXZu/Oq8OqU+76x/gcEU25nkz3EH59si/kGOxObJUFUil6pt4QjA/QSI7dzC+yQIabOfJEOH8D3q9Eb6JBRWIf26pj02b2IbWmPFEooxQXL7XNQ/eYmnrw0UhOQvBPJ+YntQmpHlJKNwPD5lIOrqvLWoUWYe5oB83o2G2CyybzuPBrioUxr4XcGFiq4W5X3rjCQpNHTPS1QOPLukisYMdXQPkcTsvcrEUHvA2bH6a2gmvG7ykR9iHqPrpARqxt1qO84RbgK/pJhNcayZKRDrNjxHxiaQJXT5xlIjld1uxAM7kRUunuWNm57gi170LveMFK668PVcUAQTrD09eosrbKQ=
+    - secure: MlwQtz4tO1mmNmPE2PIxYI552puyQpQa690C6ZOldvL0zGhw5mgj5JD8G4I4RmuaNev7mpdnBecoTEg6q2pxPTHQEgQmHVX5X7SPf1Loyes35AWzscGhWVwFdOF6ZqccB8PUZrUZ2CAD83JjG39/PGk5bxqwBNFkeFBQrGYhDuL5caqJ9/MTfKHM/NoR66ygigscnsfb8qwtS1wpSJ5LbFrC2KFzGfDXuP5bjkz9PZdQrS8c7nC63KcdeENpqwdrWWzrw3hf0uSh3xEZp7SziDZ0wMOX6lmIIzRjmlJIPF4BD9MsDiPqhmwJk4MdvKtWAzKJTnGxmygNLVw7YKnqULnWjsOmNfraHGEkqSE/DCccsjAIzYP0vD7V+JgXOk5JLvwLGff3VW9457f2pAMWJgliL9r136DKLMvxiMpXgFp3BkZHsc80Ve1G9nqgGMqp1zrCgE78mqQJ5AFQczfTZOXNsjLkGYgs38k7aLiCAm8p9ZHYBo4DZiaPKc/K2XkBmTP+2KuHpwXGUbnvfFFoHuwV1iDh+CeEo1N4UZrhwPCXTNaJKYQCQ8d7u2Vvt27Ido+IfvSnKvBlHMkpmzAdyF5dhT3jR0xEartpMw8MmUnKVxanJitfLME1qInf7INhFkkRECj9yFpFA1kCM+dszxdEEaBmD0D004xd0rU4Y3c=
 script:
-- "./gradlew clean buildAll uploadArchivesAll checkScoverage --no-daemon --stacktrace --no-build-cache --no-parallel"
+  - ./gradlew build --stacktrace
+  # scoverage 4.0.1 need scala 2.12
+  #  Execution failed for task ':reportTestScoverage'.
+  #> 'scala.collection.convert.Decorators$AsScala scala.collection.JavaConverters.asScalaBufferConverter(java.util.List)'
+  #Caused by: java.lang.NoSuchMethodError: 'scala.collection.convert.Decorators$AsScala scala.collection.JavaConverters.asScalaBufferConverter(java.util.List)'
+  #
+  # see https://github.com/scoverage/gradle-scoverage/pull/130
+  - |
+    if [[ "$TRAVIS_JDK_VERSION" == "openjdk11" && "$ORG_GRADLE_PROJECT_scalaVersion" == "2.12.10" ]]; then
+      ./gradlew checkScoverage --stacktrace
+    fi
 after_success:
-- bash <(curl -s https://codecov.io/bash)
+  - |
+    if [[ "$TRAVIS_JDK_VERSION" == "openjdk11" && "$ORG_GRADLE_PROJECT_scalaVersion" == "2.12.10" ]]; then
+      bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
+    fi
+
+deploy:
+  provider: script
+  cleanup: false
+  script: ./gradlew uploadArchives --stacktrace
+  on:
+    jdk: openjdk11
+
+before_cache:
+  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
+  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
+cache:
+  directories:
+    - $HOME/.gradle/caches/
+    - $HOME/.gradle/wrapper/
